name: Clare Goult
baseurl: /portfolio
permalink: /:year/:month/:day/:title.html
plugins:
  - jekyll-paginate
  - kramdown

paginate: 10
paginate_path: "/blog/page:num/"
# highlighter: pygments.rb # or rouge or null
markdown:    kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

