name: Clare Goult
baseurl: ""
permalink: /:year/:month/:day/:title.html
plugins:
  - jekyll-paginate
  - kramdown
  - jekyll-sitemap


paginate: 10
paginate_path: "/blog/page:num/"
# highlighter: pygments.rb # or rouge or null
markdown:    kramdown
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]

